"""empty message

Revision ID: 237a8d470149
Revises: e04f89476b9c
Create Date: 2024-01-29 17:48:43.339787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237a8d470149'
down_revision = 'e04f89476b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output_format', schema=None) as batch_op:
        batch_op.add_column(sa.Column('render_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'render_type', ['render_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('output_format', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('render_type_id')

    # ### end Alembic commands ###
