"""Added is_thinking for Google thinking models to models table

Revision ID: 3f74ed1ba35c
Revises: 701de599779b
Create Date: 2025-01-16 16:04:00.031792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f74ed1ba35c'
down_revision = '701de599779b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_thinking', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_column('is_thinking')

    # ### end Alembic commands ###
