"""Added API Vendor to Models

Revision ID: 701de599779b
Revises: 2ee3b433bd11
Create Date: 2024-03-16 11:28:26.232638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701de599779b'
down_revision = '2ee3b433bd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'api_vendor', ['api_vendor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('api_vendor_id')

    # ### end Alembic commands ###
