"""Add title field to conversations

Revision ID: fd2f7a878a33
Revises: 997618e60a77
Create Date: 2023-12-28 11:21:05.579478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2f7a878a33'
down_revision = '997618e60a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_history', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
